extensions: ["semantiva-imaging"]

# Parametric sweep (collection-based)
# Generates a collection of figures in one pipeline run and renders them to PNG frames.

pipeline:
  nodes:
  # Node 1: Generate parametric figures (single call produces multiple figures)
    - processor: ParametricLinePlotGenerator
      parameters:
        # STATIC PARAMETER: domain defines the x-axis for all plots
        domain:
          x:
            lo: -1
            hi: 2
            steps: 50
        x_label: "t"                    # STATIC: same label for all plots

      derive:
        parameter_sweep:
          # Map processor params to sweep lists. "expressions" is a mapping per sweep.
          parameters:
            expressions: "expression"
            y_label: "y_label"
            title: "title"
            line_style: "line_style"
          
          # Variables lists (zipped by_position)
          variables:
            # Range variable for x-axis (generates 50 evenly-spaced points)

            

            # 5 y expressions (each entry is {y: <expr>})
            expression:
              - {y: "50 + 5*x"}              # Linear: Center X position
              - {y: "50 + 5*x + 5*x**2"}     # Quadratic: Center Y position
              - {y: "50 + 20*x"}             # Linear: Std Dev X
              - {y: "20 + 0*x"}              # Constant: Std Dev Y
              - {y: "60 + 5*x"}              # Linear: Rotation angle
            
            # y-axis labels
            y_label:
              - "x_0(t)"
              - "y_0(t)"
              - "σ_x(t)"
              - "σ_y(t)"
              - "angle(t) [degrees]"
            
            # plot titles
            title:
              - "Center X Position: x_0(t) = 50 + 5t"
              - "Center Y Position: y_0(t) = 50 + 5t + 5t²"
              - "Standard Deviation X: σ_x(t) = 50 + 20t"
              - "Standard Deviation Y: σ_y(t) = 20 (constant)"
              - "Rotation Angle: angle(t) = 60 + 5t"
            
            # matplotlib line styles
            line_style:
              - "b-o"
              - "r-s"
              - "g-^"
              - "m-d"
              - "c-v"
          
          # mode: zip lists element-wise
          mode: by_position
          
          # Collect figures into MatplotlibFigureCollection
          collection: MatplotlibFigureCollection

  # Node 2: Render figure collection to an RGBA image stack
    - processor: FigureCollectionToRGBAStack
      parameters:
        size_px: [1200, 900]       # Output image dimensions (width, height)
        dpi: 100                    # Rendering resolution (dots per inch)
        transparent: false          # Background color (false = white)
        close_after: true           # Free memory by closing figures after render

  # Node 3: Save stack frames as numbered PNGs
    - processor: PNGRGBAImageStackSaver
      parameters:
        base_path: "param_sweep_outputs/frame"

