extensions: ["semantiva-imaging"]

# Run-space sweep (repetition-based)
# Repeats the whole pipeline once per context entry, producing independent PNGs.

pipeline:
  nodes:
  # Node 1: Generate a single parametric figure per run
    - processor: ParametricLinePlotGenerator
      parameters:
  # domain for x axis (shared)
        domain:
          x:
            lo: -1
            hi: 2
            steps: 50

  # static plot parameters
        x_label: "t"                             # X-axis label
        figure_size: [8.0, 6.0]                  # Figure dimensions in inches
        line_width: 2.0                          # Line thickness
        marker_size: 8.0                         # Marker size for plot points
        grid: true                               # Enable grid lines
        grid_alpha: 0.3                          # Grid transparency

  # run-space context will inject per-run values (e.g. expressions, title)

    # Node 2: Convert single figure to RGBA image
    # Input: MatplotlibFigure (from Node 1)
    # Output: RGBAImage (single image, not stack)
    - processor: FigureToRGBAImage
      parameters:
        size_px: [1200, 900]       # Output image dimensions (width, height)
        dpi: 100                    # Rendering resolution
        transparent: false          # Background color (false = white)
        close_after: true           # Free memory after rendering

  # Node 3: Build output path from {y_label}
    - processor: template:"run_space_plot_outputs/plot_{y_label}.png":path

    # Node 4: Save image to disk
    # Input: Path + RGBAImage (from previous nodes)
    # Output: File written to disk
    - processor: PngRGBAImageSaver

# run_space: provide per-run context lists (zipped by_position)
run_space:
  blocks:
    - mode: by_position
      context:
        expressions:
          - {y: "50 + 5*x"}
          - {y: "50 + 5*x + 5*x**2"}
          - {y: "50 + 20*x"}
          - {y: "20 + 0*x"}
          - {y: "60 + 5*x"}

        y_label:
          - "x_0(t)"
          - "y_0(t)"
          - "σ_x(t)"
          - "σ_y(t)"
          - "angle(t) [degrees]"

        title:
          - "Center X Position: x_0(t) = 50 + 5t"
          - "Center Y Position: y_0(t) = 50 + 5t + 5t²"
          - "Standard Deviation X: σ_x(t) = 50 + 20t"
          - "Standard Deviation Y: σ_y(t) = 20 (constant)"
          - "Orientation Angle: angle(t) = 60 + 5t"

        line_style:
          - "b-o"
          - "r-s"
          - "g-^"
          - "m-d"
          - "c-v"
