extensions: ["semantiva-imaging"]

# Traveling wave animation (1D)
# Produces a 48-frame animation of sin(k*x - w*t) saved as a GIF.

pipeline:
  nodes:
  # Node 1: Generate frames for traveling wave by sweeping t
    - processor: ParametricLinePlotGenerator
      derive:
        parameter_sweep:
          parameters:
            t: "t"   # Sweep the top-level scalar t
          variables:
            # Time samples over one full period [0, 2π]
            t:
              lo: 0.0
              hi: 6.283185307179586   # 2π
              steps: 48
          mode: by_position
          collection: MatplotlibFigureCollection

      parameters:
        # Domain: spatial axis showing two wavelengths (λ = 2π, x ∈ [-2π, 2π])
        domain:
          x:
            lo: -6.283185307179586   # -2π
            hi:  6.283185307179586   #  2π
            steps: 400

        # Expression with scalar parameters k, w, and t
        expressions:
          y: "sin(k*x - w*t)"

        # Scalar values (k, w). t will be overridden by the sweep.
        k: 1.0
        w: 1.0
        t: 0.0

        # Styling
        x_label: "x"
        y_label: "sin(kx - wt)"
        title: "Traveling sine wave"
        figure_size: [10.0, 4.0]
        line_style: "b-"
        line_width: 2.5
        grid: true
        grid_alpha: 0.3

  # Node 2: Render figures to an RGBA image stack
    - processor: FigureCollectionToRGBAStack
      parameters:
        size_px: [1200, 480]
        dpi: 100
        transparent: false
        close_after: true

  # Node 3: Save stack as animated GIF
    - processor: AnimatedGifRGBAImageStackSaver
      parameters:
        path: "wave_animation.gif"
